NAME = BraiiiiiiinnnzzzZ

FLAGS = -Wall -Wextra -Werror -std=c++98

SRC = main.cpp Zombie.cpp utils.cpp newZombie.cpp

CC = c++

all:
	$(CC)  $(SRC) -o $(NAME)

# clean:
# 	rm -rf $(OBJ)

# fclean:
# 	clean
# 	rm -rf $(NAME)

# re:
# 	fclean
# 	all


